[package]
name = "untitled1"
version = "0.1.0"
authors = ["load28 <tjalsdud89@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"